import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import Image from 'next/image';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className='relative'>{children}</body>
		</html>
	);
}
